command: [
  "gunicorn",
  "databricks_app:app",
  "-w", "2",
  "-k", "uvicorn.workers.UvicornWorker",
  "--bind", "0.0.0.0:8000",
  "--timeout", "300"
]

env:
  - name: 'DATABRICKS_HTTP_PATH'
    value: '/sql/1.0/warehouses/fc63b669d98bde08'
  - name: 'DATABRICKS_SERVER_HOSTNAME'
    value: 'fe-vm-mv-serverless-tixx4d.cloud.databricks.com'

